---
title: "Shorebird Analysis"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(readr)
library(dplyr)
library(janitor)
library(ggplot2)
```

```{r}
webpage <- read_html("https://www.pwrc.usgs.gov/bbl/manual/speclist.cfm")

tbls <- html_nodes(webpage, "table") %>%    #this is in the rvest package
    html_table(fill = TRUE)

species <- tbls[[1]] %>% 
    clean_names() %>%       #this is in the janitor package
    select(alpha_code, common_name) %>% 
    mutate(alpha_code = tolower(alpha_code))
```

```{r}
predator_surveys<- read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A9ffec04c-7e2d-41dd-9e88-b6c2e8c4375e")

nest_data <- read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A982bd2fc-4edf-4da7-96ef-0d11b853102d")
```

```{r}

add_species_name <- function(df){
new.df <- df %>% left_join(species, by=c("species" = "alpha_code"))
if(is.na(new.df))
return(new.df)
}

predator_surveys_wname<- add_species_name(predator_surveys)
nest_data_wname<- add_species_name(nest_data)
```

Advanced version of the simple function looks like this:

```{r}
#' Function to add common name to data.frame according to the BBL list of species codes

#' @param df A data frame containing BBL species codes in column `species`
#' @param species A data frame defining BBL species codes with columns `alpha_code` and `common_name`
#' @return A data frame with original data df, plus the common name of species

assign_species_name <- function(df, species){
    if (!("alpha_code" %in% names(species)) |
        !("species" %in% names(df)) |
        !("common_name" %in% names(species))){
      stop("Tables appear to be formatted incorrectly.")
    }  
  
    return_df <- left_join(df, species, by = c("species" = "alpha_code"))
    
    if (nrow(return_df) > nrow(df)){
      warning("Joined table has more rows than original table. Check species table for duplicated code values.")
    }
    
    if (length(which(is.na(return_df$common_name))) > 0){
      x <- length(which(is.na(return_df$common_name)))
      warning(paste("Common name has", x, "rows containing NA"))
    }
    
    return(return_df)
        
}

predator_surveys_wname<- assign_species_name(predator_surveys,species)
nest_data_wname<- assign_species_name(nest_data,species)

```

When no predators were observed 

```{r}
predator_count<- predator_surveys_wname %>% 
  group_by(year,common_name) %>% 
  summarise(sum = sum(count,na.rm = T)) %>% 
  filter(!is.na(common_name))

my_theme <- theme_classic()+
  theme(legend.position = "bottom", legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, hjust=1))

ggplot(predator_count, aes(color=common_name, y=sum, x=year))+
  geom_line()+
  geom_point()+
  ylab("Predator Count")+
  xlab("")+
  my_theme

```

```{r}
predated_egg_count <- nest_data_wname %>% 
  group_by(year, common_name) %>% 
  summarise(sum=sum(number_eggs_predated,na.rm=T)) %>% 
  filter(!is.na(common_name))

ggplot(predated_egg_count,aes(x=year,y=sum,color=common_name))+
  geom_line()+
  geom_point()+
  ylab("Number Eggs Predated")+
  xlab("")+
  my_theme
```

```{r}
total_predator<- predator_count %>% 
  group_by(year) %>% 
  summarise(total.preds=sum(sum,na.rm = T),.groups="drop") # .groups = "drop" just makes it not show the warning message that groups are being dropped automatically

egg_pred_join <- predated_egg_count %>% 
  left_join(total_predator, by=c("year" = "year"))

ggplot(egg_pred_join,aes(x=total.preds,y=sum))+
  geom_point()+
  ylab("Eggs predated")+
  xlab("Total number of predators")+
  facet_wrap(~ common_name, scales= "free_y", ncol=4)+
  theme_bw()

```